# AWS Proton service template input schema (scaffold)
schema:
  name: shieldcraft-lambda
  description: Service template inputs for a VPC-attached Lambda function
  format:
    openapi: "3.0.0"
  input:
    type: object
    properties:
      AppName:
        type: string
        description: Application name for tagging
      Domain:
        type: string
        description: Business domain for tagging
      EnvironmentName:
        type: string
        enum: [dev, staging, prod]
      FunctionName:
        type: string
      Handler:
        type: string
        default: index.handler
      Runtime:
        type: string
        default: python3.12
      CodeS3Bucket:
        type: string
      CodeS3Key:
        type: string
      RoleArn:
        type: string
      VpcId:
        type: string
      SubnetIds:
        type: array
        items:
          type: string
      SecurityGroupIds:
        type: array
        items:
          type: string
    required:
      - AppName
      - Domain
      - EnvironmentName
      - FunctionName
      - Handler
      - Runtime
      - CodeS3Bucket
      - CodeS3Key
      - RoleArn
      - VpcId
      - SubnetIds
      - SecurityGroupIds
