import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Custom sidebar that uses draft: true in ADR frontmatter to hide from sidebar
const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    { type: 'link', label: 'Analyst Dashboard', href: '/analyst-dashboard' },
    { type: 'link', label: 'Documentation', href: '/documentation' },
    { type: 'link', label: 'Plugins', href: '/plugins' },
    { type: 'link', label: 'Pricing', href: '/pricing' },
    { type: 'autogenerated', dirName: '.' },
  ],
};

export default sidebars;
