import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Custom sidebar that uses draft: true in ADR frontmatter to hide from sidebar
const sidebars: SidebarsConfig = {
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
