lakeformation:
  admin_role: ShieldCraftLakeAdmin
  buckets:
    - id: AnalyticsDataBucket
      name: shieldcraft-dev-analytics
    - id: RawDataBucket
      name: shieldcraft-dev-raw
    - id: ProcessedDataBucket
      name: shieldcraft-dev-processed
data_quality: {}
cloud_native_hardening:
  enable_cloudwatch_alarms: false
  alarm_email: devops@shieldcraft.ai
  config_rules:
    - s3-bucket-public-read-prohibited
    - iam-user-no-policies-check
chunking:
  strategy: fixed
  fixed:
    chunk_size: 128
    min_length: 32
    overlap: 8
ai_core:
  model_name: stub
  device: cpu
  quantize: false
app:
  env: dev
  region: af-south-1
  account: "879584803102"
  resource_prefix: shieldcraft-dev
  log_level: DEBUG
  enable_feature_x: true
airbyte:
  deployment_type: ecs
  max_task_count: 3
  min_task_count: 1
  mode: ecs_scale_to_zero
beir:
  batch_size: 32
  data_path: ./beir_datasets
  datasets:
    - scifact
  output_path: beir_results.json
drift_scan_schedule: {}

embedding:
  provider: stub
  model: stub
  device: cpu
eventbridge:
  rules: []
glue:
  database_name: shieldcraft_dev_db
msk:
  cluster:
    name: shieldcraft-dev-msk
    broker_count: 2
    client_subnets: []
    security_groups: []
    kafka_version: 2.8.1
mteb:
  batch_size: 32
  data_path: ./mteb_datasets
  datasets:
    - scifact
  output_path: mteb_results.json
networking: {}
secrets:
  glue_db_admin_password:
    name: shieldcraft-dev-glue-db-admin-secret
    description: Glue DB admin credential for dev
    generate: true
    generate_key: REDACTED
  airbyte_source_db_password:
    name: shieldcraft-dev-airbyte-source-db-secret
    description: Airbyte source DB credential for dev
    generate: true
    generate_key: REDACTED
  opensearch_admin_password:
    name: shieldcraft-dev-opensearch-admin-secret
    description: OpenSearch admin credential for dev
    generate: true
    generate_key: REDACTED
  sagemaker_model_registry_password:
    name: shieldcraft-dev-sagemaker-model-registry-secret
    description: SageMaker model registry DB credential for dev
    generate: true
    generate_key: REDACTED
  third_party_api_key:
    name: shieldcraft-dev-third-party-api-key
    description: API key for external service in dev
    generate: false
    template: '{"api_key": "your-key-here"}'
  kafka_scram_credentials:
    name: shieldcraft-dev-kafka-scram-credentials
    description: SASL/SCRAM credentials for external Kafka (dev)
    generate: false
    template: '{"username": "devuser", "secret": "REDACTED"}'
