orchestrator:
  output_dir: orch_results/staging
  max_workers: 4
  retry: 2
  log_level: INFO
drift_scan_schedule: weekly
chunking:
  strategy: semantic
  fixed:
    chunk_size: 384
    overlap: 32
    min_length: 96
  semantic:
    min_length: 96
  recursive:
    max_chunk_size: 384
    min_length: 96
  sentence:
    min_length: 48
  token_based:
    chunk_size: 192
    overlap: 16
    min_length: 48
    tokenizer: dummy
  sliding_window:
    window_size: 192
    step_size: 96
    min_length: 48
  custom_heuristic:
    delimiter: "\n---\n"
    min_length: 48
    rules: {}
app:
  env: staging
  region: af-south-1
  account: "879584803102"
  resource_prefix: shieldcraft-staging
  log_level: INFO
  enable_feature_x: false
networking:
  vpc_id: vpc-shieldcraft-staging
  cidr: "10.1.0.0/16"
  subnets:
    - id: subnet-pub-a
      cidr: "10.1.10.0/24"
      type: PUBLIC
    - id: subnet-priv-a
      cidr: "10.1.1.0/24"
      type: PRIVATE
    - id: subnet-priv-b
      cidr: "10.1.2.0/24"
      type: PRIVATE
  security_groups:
    - id: sg-msk
      description: Security group for MSK brokers
      allow_all_outbound: true
    - id: sg-lambda
      description: Security group for Lambda functions
      allow_all_outbound: true
    - id: sg-default
      description: Default security group for ShieldCraft staging VPC
      allow_all_outbound: true
s3:
  buckets:
    - id: RawDataBucket
      name: shieldcraft-staging-raw
      versioned: true
      encryption: S3_MANAGED
      block_public_access: BLOCK_ALL
      removal_policy: DESTROY
      lifecycle_rules:
        - id: transition-raw-staging
          enabled: true
          transitions:
            - days: 60
              storage_class: STANDARD_IA
            - days: 120
              storage_class: GLACIER
          expiration_days: 730
          abort_incomplete_multipart_upload_days: 7
    - id: ProcessedDataBucket
      name: shieldcraft-staging-processed
      versioned: true
      encryption: S3_MANAGED
      block_public_access: BLOCK_ALL
      removal_policy: DESTROY
      lifecycle_rules:
        - id: transition-processed-staging
          enabled: true
          transitions:
            - days: 60
              storage_class: STANDARD_IA
            - days: 120
              storage_class: GLACIER
          expiration_days: 730
          abort_incomplete_multipart_upload_days: 7
    - id: AnalyticsDataBucket
      name: shieldcraft-staging-analytics
      versioned: true
      encryption: S3_MANAGED
      block_public_access: BLOCK_ALL
      removal_policy: DESTROY
      lifecycle_rules:
        - id: transition-analytics-staging
          enabled: true
          transitions:
            - days: 60
              storage_class: STANDARD_IA
            - days: 120
              storage_class: GLACIER
          expiration_days: 730
          abort_incomplete_multipart_upload_days: 7
  lifecycle_policy_days: 60
  enable_access_logs: true
glue:
  database_name: shieldcraft_staging_db
  crawler_schedule: cron(0 2 * * ? *)
  enable_data_quality: true
msk:
  mode: managed # external (dev) | managed (staging/prod)
  security_group:
    id: MskSecurityGroup
    description: Security group for MSK brokers
    allow_all_outbound: true
  cluster:
    id: ShieldCraftMskCluster
    name: shieldcraft-msk-cluster-staging
    kafka_version: 3.5.1
    number_of_broker_nodes: 3
    instance_type: kafka.m5.large
    enhanced_monitoring: PER_TOPIC_PER_BROKER
    client_authentication:
      sasl_scram: false
      tls: true
    encryption_in_transit:
      client_broker: TLS
      in_cluster: true
    public_access: false
    vpc_subnet_ids:
      - subnet-priv-a
      - subnet-priv-b
    security_group_ids:
      - sg-msk
lambda_:
  functions:
    - id: MskTopicCreator
      description: Lambda to create Kafka topics after MSK cluster is ready
      handler: msk_topic_creator.lambda_handler
      runtime: python{{ PYTHON_VERSION }}
      memory_size: 256
      timeout: 60
      environment:
        MSK_CLUSTER_NAME: shieldcraft-msk-cluster-staging
        TOPICS:
          - name: events-ingest
            partitions: 3
            replication_factor: 2
          - name: audit-log
            partitions: 2
            replication_factor: 2
      vpc_subnet_ids:
        - subnet-priv-a
        - subnet-priv-b
      security_group_ids:
        - sg-lambda
      policies:
        - kafka:DescribeCluster
        - kafka:GetBootstrapBrokers
        - kafka:CreateTopic
        - kafka:ListTopics
        - kafka:DescribeTopic
opensearch:
  mode: managed # none (dev) | managed | self_managed
  security_group:
    id: OpenSearchSecurityGroup
    description: Security group for OpenSearch
    allow_all_outbound: true
  domain:
    id: ShieldCraftOpenSearchDomain
    name: shieldcraft-opensearch-staging
    engine_version: OpenSearch_2.11
    cluster_config:
      instanceType: t3.small.search
      instanceCount: 2
    node_to_node_encryption_options:
      enabled: true
    encryption_at_rest_options:
      enabled: true
    ebs_options:
      ebsEnabled: true
      volumeSize: 20
      volumeType: gp3
airbyte:
  mode: ecs_managed # local | ecs_scale_to_zero (dev) | ecs_managed
  deployment_type: ecs
  min_task_count: 1
  max_task_count: 3
data_quality:
  mode: managed # inline (dev) | managed
  dq_framework: deequ
  dq_schedule: cron(0 3 * * ? *)
lakeformation:
  admin_role: ShieldCraftLakeAdmin
  data_lake_location: s3://shieldcraft-staging-analytics
  buckets:
    - id: AnalyticsDataBucket
      name: shieldcraft-staging-analytics
    - id: RawDataBucket
      name: shieldcraft-staging-raw
    - id: ProcessedDataBucket
      name: shieldcraft-staging-processed
  permissions:
    - template: etl
      principal: GLUE_EXECUTION_ROLE_ARN
      resource_type: table
      resource:
        databaseName: shieldcraft_staging_db
        tableName: raw_data
    - template: admin
      principal: LAKEFORMATION_ADMIN_ROLE_ARN
      resource_type: database
      resource:
        databaseName: shieldcraft_staging_db
    - principal: SAGEMAKER_EXECUTION_ROLE_ARN
      resource_type: bucket
      resource:
        arn: arn:aws:s3:::shieldcraft-staging-analytics
      actions: ["DATA_LOCATION_ACCESS"]
sagemaker:
  mode: managed # local (dev) | managed
  training_instance_type: ml.m5.xlarge
  inference_instance_type: ml.m5.large
  endpoint_auto_scaling: true
  model_registry: shieldcraft-model-registry-staging
cloud_native_hardening:
  enable_cloudwatch_alarms: true
  alarm_email: devops@shieldcraft.ai
  config_rules:
    - s3-bucket-public-read-prohibited
    - iam-user-no-policies-check
tags:
  project: shieldcraft-ai
  environment: staging
  owner: ai-solutions
  cost_center: RND
  team: mlops
  compliance: standard
eventbridge:
  data_bus_name: shieldcraft-staging-data-bus
  security_bus_name: shieldcraft-staging-security-bus
  lambda_export_name: StagingMskTopicCreatorLambdaArn
  data_event_source: shieldcraft.data.staging
stepfunctions:
  state_machines:
    - id: DataIngestAndValidate
      name: shieldcraft-staging-data-ingest-validate
      role_arn: arn:aws:iam::123456789012:role/ShieldCraftStepFnRole
      comment: "Orchestrates data ingestion, validation, and error handling"
      definition:
        - id: IngestData
          type: Task
          resource: arn:aws:lambda:af-south-1:123456789012:function:IngestDataLambda
          next: ValidateData
          catch:
            - handler: HandleIngestError
              errors: ["States.ALL"]
        - id: ValidateData
          type: Task
          resource: arn:aws:lambda:af-south-1:123456789012:function:ValidateDataLambda
          next: IsValid
        - id: IsValid
          type: Choice
          choices:
            - condition: string_equals
              args: ["$.validationResult", "PASS"]
              next: Success
            - condition: string_equals
              args: ["$.validationResult", "FAIL"]
              next: HandleValidationError
          default: HandleValidationError
        - id: Success
          type: Pass
          end: true
        - id: HandleIngestError
          type: Pass
          end: true
        - id: HandleValidationError
          type: Pass
          end: true
    - id: BenchmarkAndValidate
      name: shieldcraft-staging-benchmark-validate
      role_arn: arn:aws:iam::123456789012:role/ShieldCraftStepFnRole
      comment: "Orchestrates BEIR/MTEB benchmarking and model validation (staging: full orchestration)"
      definition:
        - id: RunBEIRBenchmark
          type: Task
          resource: arn:aws:lambda:af-south-1:123456789012:function:RunBEIRBenchmarkLambda
          next: RunMTEBBenchmark
          catch:
            - handler: HandleBenchmarkError
              errors: ["States.ALL"]
        - id: RunMTEBBenchmark
          type: Task
          resource: arn:aws:lambda:af-south-1:123456789012:function:RunMTEBBenchmarkLambda
          next: ValidateBenchmarkResults
          catch:
            - handler: HandleBenchmarkError
              errors: ["States.ALL"]
        - id: ValidateBenchmarkResults
          type: Task
          resource: arn:aws:lambda:af-south-1:123456789012:function:ValidateBenchmarkResultsLambda
          next: Success
          catch:
            - handler: HandleBenchmarkError
              errors: ["States.ALL"]
        - id: Success
          type: Pass
          end: true
        - id: HandleBenchmarkError
          type: Pass
          end: true
ai_core:
  model_name: "mistralai/Mistral-7B-v0.1"
  quantize: true
  device: "cuda"
embedding:
  model_name: "sentence-transformers/all-MiniLM-L6-v2"
  quantize: true
  device: "cuda"
vector_store:
  db_host: "staging-db-host"
  db_port: 5432
  db_name: "shieldcraft_vectors_staging"
  db_user: "postgres"
  db_password: "REDACTED"
  table_name: "embeddings"
  batch_size: 100
beir:
  datasets: ["scifact", "trec-covid"]
  data_path: "./beir_datasets"
  output_path: "beir_results_staging.json"
  batch_size: 32
mteb:
  tasks: null
  output_path: "mteb_results_staging.json"
  batch_size: 32
