#!/bin/bash
# Debug auth state after login

echo "🔍 Debugging Authentication State"
echo "=================================="
echo ""
echo "📋 Test Steps:"
echo ""
echo "1. Open your browser console (F12)"
echo "2. Go to http://localhost:3000"
echo "3. Click 'Login' button"
echo "4. Complete Google OAuth"
echo "5. Watch the console logs:"
echo ""
echo "   You should see:"
echo "   ✅ 'Auth change event received: {authenticated: true, user: {...}}'"
echo "   ✅ 'checkAuth - authenticated: true'"
echo "   ✅ 'checkAuth - user: {email: \"...\", ...}'"
echo ""
echo "   If you see:"
echo "   ❌ 'checkAuth - authenticated: false'"
echo "   Then Amplify fetchAuthSession() is not returning tokens"
echo ""
echo "6. After redirect, the button should show: yourname@email.com [Logout]"
echo ""
echo "🔧 If still not working, run these in browser console:"
echo ""
echo "   // Check if Amplify has tokens:"
echo "   import { fetchAuthSession } from 'aws-amplify/auth';"
echo "   const session = await fetchAuthSession();"
echo "   // Inspect `session.tokens` in the console (e.g. session.tokens.accessToken)"
echo ""
echo "   // Manually trigger auth check:"
echo "   import { notifyAuthChange } from '@site/src/utils/auth-cognito';"
echo "   await notifyAuthChange();"
echo ""
echo "📝 Key Changes Made:"
echo "   1. ✅ Fixed onAuthChange callback signature (2 params, not 1)"
echo "   2. ✅ Added notifyAuthChange() to properly update all listeners"
echo "   3. ✅ Increased OAuth callback timeout to 1000ms (was 500ms)"
echo "   4. ✅ Added debug-only logging to auth.tsx"
echo "   5. ✅ Reset user to null when not authenticated"
echo ""
echo "🎯 The login button should now update immediately after OAuth!"
