name: Inject Amplify Config from Secrets Manager (template)

on:
  workflow_dispatch:
    inputs:
      run_build:
        description: "Run npm build after injecting config? (yes/no)"
        required: false
        default: "no"

jobs:
  inject-amplify-config:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (assume role via OIDC)
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.ROLE_TO_ASSUME }}
          aws-region: af-south-1

      - name: Fetch Amplify config from Secrets Manager
        env:
          SECRET_NAME: ${{ secrets.SECRET_NAME }}
        run: |
          set -euo pipefail
          echo "Fetching secret: $SECRET_NAME"
          mkdir -p docs-site/static
          aws secretsmanager get-secret-value --secret-id "$SECRET_NAME" --query SecretString --output text > docs-site/static/amplify-config.json
          echo "Wrote docs-site/static/amplify-config.json (preview:)"
          head -c 400 docs-site/static/amplify-config.json || true

      - name: Run docs-site build (optional)
        if: "${{ github.event.inputs.run_build == 'yes' }}"
        run: |
          cd docs-site
          npm ci
          npm run build
