name: Playwright E2E (docs-site)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Build and run Playwright tests
        run: |
          cd docs-site
          npm ci
          npx playwright install --with-deps
          npm run build
          npx playwright test tests/e2e --project=chromium --reporter=dot,junit
